import torch
import torch.nn as nn
import torch.nn.functional as F

from .hypernetwork import HyperNetwork


class QNetwork(nn.Module):
    def __init__(self, state_dim, action_dim, hidden_dims):
        super().__init__()
        dims = [state_dim + action_dim] + list(hidden_dims) + [1]
        layers = []
        for i in range(len(dims) - 2):
            layers.append(nn.Linear(dims[i], dims[i + 1]))
            layers.append(nn.ReLU())
        layers.append(nn.Linear(dims[-2], dims[-1]))
        self.net = nn.Sequential(*layers)

    def forward(self, state, action):
        return self.net(torch.cat([state, action], dim=-1))


class TwinCritic(nn.Module):
    """
    TD3-style twin critics to reduce overestimation.
    """

    def __init__(self, state_dim, action_dim, hidden_dims=(256, 256)):
        super().__init__()
        self.q1_net = QNetwork(state_dim, action_dim, hidden_dims)
        self.q2_net = QNetwork(state_dim, action_dim, hidden_dims)

    def forward(self, state, action):
        return self.q1_net(state, action), self.q2_net(state, action)

    def q1(self, state, action):
        return self.q1_net(state, action)


class HyperQNetwork(nn.Module):
    """
    Local Q network whose weights are generated from agent metadata.
    """

    def __init__(self, state_dim, action_dim, meta_dim, hidden_dims, hyper_hidden, dropout=0.0):
        super().__init__()
        self.input_dim = state_dim + action_dim
        self.dims = [self.input_dim] + list(hidden_dims) + [1]
        self.layout = self._build_layout()
        self.param_dim = self.layout[-1][-1]
        self.hypernet = HyperNetwork(meta_dim, hyper_hidden, self.param_dim, dropout=dropout)

    def _build_layout(self):
        layout = []
        offset = 0
        for in_dim, out_dim in zip(self.dims[:-1], self.dims[1:]):
            weight_numel = out_dim * in_dim
            bias_numel = out_dim
            layout.append((out_dim, in_dim, offset, offset + weight_numel, offset + weight_numel + bias_numel))
            offset += weight_numel + bias_numel
        return layout

    def forward(self, state, action, meta):
        # state/action/meta: [B, N, D]. Each node receives its own generated Q network.
        theta = self.hypernet(meta)
        x = torch.cat([state, action], dim=-1)

        for layer_idx, (out_dim, in_dim, weight_start, bias_start, end) in enumerate(self.layout):
            weight = theta[..., weight_start:bias_start].view(*theta.shape[:-1], out_dim, in_dim)
            bias = theta[..., bias_start:end].view(*theta.shape[:-1], out_dim)
            x = torch.einsum('bni,bnoi->bno', x, weight) + bias
            if layer_idx < len(self.layout) - 1:
                x = F.relu(x)

        return x


class HyperTwinCritic(nn.Module):
    """
    HypeMARL-style twin local critics generated by two critic hypernetworks.
    """

    def __init__(
        self,
        state_dim,
        action_dim,
        meta_dim,
        hidden_dims=(256,),
        hyper_hidden=(256, 512),
        dropout=0.0,
    ):
        super().__init__()
        self.q1_net = HyperQNetwork(state_dim, action_dim, meta_dim, hidden_dims, hyper_hidden, dropout=dropout)
        self.q2_net = HyperQNetwork(state_dim, action_dim, meta_dim, hidden_dims, hyper_hidden, dropout=dropout)

    def forward(self, state, action, meta, reduce=True):
        q1 = self.q1_net(state, action, meta)
        q2 = self.q2_net(state, action, meta)
        if reduce:
            return q1.mean(dim=1), q2.mean(dim=1)
        return q1, q2

    def q1(self, state, action, meta, reduce=True):
        q1 = self.q1_net(state, action, meta)
        return q1.mean(dim=1) if reduce else q1
